#!/usr/bin/env bash
# Copyright (c) 2026 Brian J. Fox
# Licensed under GPLv2 with the GPLv2-AI Exception.
#
# run_diff_corpus_exec.sh GNASH BASH [CORPUS_NUL]
#
# Corpus-scale EXECUTION differential.  Reads a NUL-delimited corpus of shell
# snippets (default: generated by gen_corpus.sh) and runs each under gnash and a
# real bash with `-c`, comparing stdout AND exit status.  Same contract as
# run_diff.sh, but over an order of magnitude more, machine-generated inputs.
#
# SAFETY: each snippet runs inside a throwaway sandbox directory with a bounded
# timeout and a scrubbed, minimal environment.  The default corpus is entirely
# self-authored (side-effect-free) -- do NOT point this at harvested/untrusted
# scripts; that is what the *parse* differential (no execution) is for.
set -u

gnash=${1:?usage: run_diff_corpus_exec.sh GNASH BASH [CORPUS_NUL]}
bash_bin=${2:?usage: run_diff_corpus_exec.sh GNASH BASH [CORPUS_NUL]}
corpus=${3:-}

# Resolve binaries to absolute paths: run_snip cd's into the sandbox, which would
# break any relative path (e.g. build/core/gnash) and yield a bogus 127.
abspath() { case "$1" in /*) printf '%s' "$1";; *) printf '%s/%s' "$(pwd)" "$1";; esac; }
[ -x "$gnash" ] && gnash=$(abspath "$gnash")

is_real_bash() { "$1" --version 2>/dev/null | head -1 | grep -qi 'GNU bash'; }
if ! is_real_bash "$bash_bin"; then
  found=""
  for cand in "${GNASH_BASH:-}" /opt/homebrew/Cellar/bash/*/bin/bash \
              /usr/local/bin/bash /opt/local/bin/bash /bin/bash; do
    if [ -n "$cand" ] && [ -x "$cand" ] && is_real_bash "$cand"; then found=$cand; break; fi
  done
  [ -z "$found" ] && { echo "no real bash oracle found; skipping" >&2; exit 0; }
  bash_bin=$found
fi

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if [ -z "$corpus" ]; then
  corpus=$(mktemp)
  "$bash_bin" "$here/gen_corpus.sh" > "$corpus"
fi

sandbox=$(mktemp -d)
outf="$sandbox/.stdout"
trap 'rm -rf "$sandbox"' EXIT

# Prefer a real timeout(1) if one is installed; otherwise fall back to a manual
# watcher.  Crucially, stdout is captured to a FILE (not a command substitution),
# so the background watcher can never hold the capture pipe open -- the bug that
# made an earlier version add ~10s of latency per snippet.
TIMEOUT_BIN=$(command -v timeout || command -v gtimeout || true)

# Sets globals SNIP_RC and SNIP_OUT for a snippet run under $1 in the sandbox.
run_snip() {
  local sh=$1 snip=$2
  : > "$outf"
  if [ -n "$TIMEOUT_BIN" ]; then
    ( cd "$sandbox" && env -i PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin" \
        HOME="$sandbox" TMPDIR="$sandbox" LC_ALL=C \
        "$TIMEOUT_BIN" -k 1 10 "$sh" -c "$snip" </dev/null >"$outf" 2>/dev/null )
    SNIP_RC=$?
  else
    ( cd "$sandbox" && env -i PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin" \
        HOME="$sandbox" TMPDIR="$sandbox" LC_ALL=C \
        "$sh" -c "$snip" </dev/null >"$outf" 2>/dev/null ) &
    local pid=$!
    ( sleep 10; kill -9 "$pid" 2>/dev/null ) >/dev/null 2>&1 &
    local w=$!
    wait "$pid" 2>/dev/null; SNIP_RC=$?
    kill "$w" 2>/dev/null; wait "$w" 2>/dev/null
  fi
  SNIP_OUT=$(cat "$outf")
}

total=0 match=0 fails=0
report=${GNASH_REPORT:-run_diff_corpus_exec.report}
: > "$report"

while IFS= read -r -d '' snip; do
  [ -n "$snip" ] || continue
  total=$((total + 1))
  run_snip "$gnash" "$snip";    g_rc=$SNIP_RC; g_out=$SNIP_OUT
  run_snip "$bash_bin" "$snip"; b_rc=$SNIP_RC; b_out=$SNIP_OUT
  if [ "$g_out" = "$b_out" ] && [ "$g_rc" = "$b_rc" ]; then
    match=$((match + 1))
  else
    fails=$((fails + 1))
    {
      echo "MISMATCH: $snip"
      echo "  gnash (rc=$g_rc): $g_out"
      echo "  bash  (rc=$b_rc): $b_out"
      echo "---"
    } >> "$report"
  fi
done < "$corpus"

pct="n/a"
[ "$total" -gt 0 ] && pct=$(awk "BEGIN{printf \"%.1f\", 100*$match/$total}")
echo "=== corpus execution differential ==="
echo "snippets     : $total"
echo "match        : $match"
echo "mismatch     : $fails"
echo "AGREEMENT    : $match/$total = ${pct}%"
echo "divergences -> $report"
[ "$fails" -eq 0 ]
